"""
Django settings for my_django_payments project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-qc_rs_k2mr1--7nw+v5e)fyg&f3lmq92$0tx*&do_v57ps93ty'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'getpaid',         # django-getpaid - system płatności
    'getpaid_payu',    # Plugin PayU dla django-getpaid
    'products.apps.ProductsConfig',        # Twoja aplikacja
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'my_django_payments.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'my_django_payments.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================================================
# DJANGO-GETPAID CONFIGURATION
# ============================================================================

# Model zamówienia - musi implementować interfejs OrderInterface
GETPAID_ORDER_MODEL = 'products.Order'

# URL-e przekierowań po płatności
GETPAID_SUCCESS_URL_NAME = 'payment:success'  # Nazwa URL dla sukcesu
GETPAID_FAILURE_URL_NAME = 'payment:failure'  # Nazwa URL dla błędu

# Konfiguracja backendu płatności PayU
GETPAID_BACKEND_SETTINGS = {
    'getpaid_payu.processor.PayuProcessor': {
        # Dane testowe PayU Sandbox
        'pos_id': '300746',  # ID punktu płatności (sandbox)
        'second_key': 'b6ca15b0d1020e8094d9b5f8d163db54',  # Drugi klucz (sandbox)
        'oauth_id': '300746',  # Client ID OAuth (sandbox)
        'oauth_secret': '2ee86a66e5d97e3fadc400c9f19b065d',  # Client Secret OAuth (sandbox)
        'sandbox': True,  # Tryb testowy
    },
}

# ============================================================================
# USTAWIENIA LOGOWANIA I REJESTRACJI
# ============================================================================

LOGIN_REDIRECT_URL = 'payment:product_list'
LOGIN_URL = 'payment:login'
LOGOUT_REDIRECT_URL = 'payment:product_list'